'use strict';
const T=document.querySelector('#teacherApp'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let classId='601',students=[],lastAt=null,query='',onlyIncomplete=false,opened='',timer=null,requestSeq=0;
async function api(url,data){const res=await fetch(url,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const b=await res.json();if(!res.ok){const e=Error(b.error);e.status=res.status;throw e;}return b;}
function count(s){return s.awards.length;}
function currentCount(s){return Rules.stages.filter(stage=>Rules.completed(stage.id,s.payload.records[stage.id])).length;}
function time(v){return v?new Date(v).toLocaleTimeString('zh-CN',{hour12:false}):'尚无记录';}
function entry(){clearInterval(timer);document.querySelector('#teacherLogout').hidden=true;document.querySelector('#teacherTestLink').hidden=true;T.innerHTML='<section class="login-card" style="max-width:440px;margin:8vh auto"><div class="eyebrow">教师入口</div><h2>查看学习过程</h2><p class="muted">教师大屏密码为 <b>teacher</b>。</p><form id="teacherForm"><label for="teacherPassword">教师密码</label><input id="teacherPassword" type="password" autocomplete="current-password" required><button class="primary">进入班级大屏</button></form><p class="error" id="teacherError" role="alert"></p></section>';document.querySelector('#teacherForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/teacher/login',{password:document.querySelector('#teacherPassword').value});await start();}catch(err){document.querySelector('#teacherError').textContent=err.message;}};}
async function start(){document.querySelector('#teacherLogout').hidden=false;document.querySelector('#teacherTestLink').hidden=false;T.innerHTML='<div class="task-heading"><div><div class="eyebrow">课堂观察 / 我是小小控制员</div><h1 style="font-size:29px;margin:0">看见学生怎样控制、怎样修改</h1></div><span id="updated" class="status">正在读取课堂记录…</span></div><div class="teacher-toolbar"><label for="teacherClass">班级</label><select id="teacherClass">'+['601','602','603','604','605','606'].map(c=>'<option value="'+c+'" '+(c===classId?'selected':'')+'>'+c+'班</option>').join('')+'</select><input id="studentSearch" aria-label="查找姓名" placeholder="查找姓名"><button id="filterIncomplete">只看未完成</button><button id="exportClass">导出当前班级记录</button></div><div id="classContent"></div>';document.querySelector('#teacherClass').onchange=e=>{classId=e.target.value;opened='';students=[];renderClass();load();};document.querySelector('#studentSearch').oninput=e=>{query=e.target.value;renderClass();};document.querySelector('#filterIncomplete').onclick=e=>{onlyIncomplete=!onlyIncomplete;e.target.classList.toggle('selected',onlyIncomplete);renderClass();};document.querySelector('#exportClass').onclick=()=>{const b=new Blob([JSON.stringify({lesson:'我是小小控制员',classId,exportedAt:new Date().toISOString(),students},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=classId+'班-配送实验记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};await load();clearInterval(timer);timer=setInterval(load,4000);}
async function load(){const seq=++requestSeq,requested=classId;try{const d=await api('/api/teacher/class?class='+requested);if(seq!==requestSeq||requested!==classId)return;students=d.students;lastAt=d.at;renderClass();document.querySelector('#updated').textContent='自动更新 · '+time(lastAt);document.querySelector('#updated').className='status';}catch(e){if(e.status===401){entry();return;}if(document.querySelector('#updated')){document.querySelector('#updated').textContent='连接异常 · 当前显示 '+time(lastAt)+' 的记录';document.querySelector('#updated').className='status warning';}}}
function observedScore(s,first=false){return Rules.assessmentScore(s.payload.records.assessment,first?'first':'latest');}
function observedTotal(s,first=false){const r=s.payload.records.assessment,attempt=first?r?.first:r?.history?.[r.history.length-1];return attempt?Rules.assessmentTotal(attempt):QuizBank.count;}
function detail(s){
 const r=s.payload.records,m=r.manual,d=r.design,o=r.obstacle,pg=r.program,rb=r.robot;
 const control=m?.situation&&m?.keyAction&&m?.outcome?m.situation+' → '+m.keyAction+' → '+m.outcome:'尚无完整证据';
 const firstProgram=pg?.history?.[0],latestProgram=pg?.history?.[pg.history.length-1];
 const robotFeatures=rb?.sheet?.functions?.map(f=>f.kind==='custom'?f.custom:f.kind).filter(Boolean).join('、')||'尚无作品';
 return '<div class="detail-grid"><div><h3>操作与设计证据</h3>'
 +'<p><b>导入首答：</b>'+E(r.intro?.first?JSON.stringify(r.intro.first):'尚无证据')+'</p>'
 +'<p><b>手动控制：</b>'+E(m?.actions?.filter(x=>x!=='tick').slice(-30).join(' → ')||'尚无证据')+'</p>'
 +'<p><b>关键控制证据：</b>'+E(control)+'</p>'
 +'<p><b>首次任务方案：</b>'+E(d?.first?.steps?.join(' → ')||'尚无证据')+'</p>'
 +'<p><b>最近测试：</b>'+E(d?.result||'尚无证据')+'</p>'
 +'<p><b>机器人设计：</b>'+E(robotFeatures)+'；'+E(rb?.sheet?.instructionExample||'内部指令尚未填写')+'</p></div>'
 +'<div><h3>验证与后续支持</h3>'
 +'<p><b>障碍预测：</b>'+E(o?.prediction||'尚无证据')+'；<b>所选规则：</b>'+E(o?.policy||'尚无证据')+'</p>'
 +'<p><b>程序调试：</b>'+E(firstProgram?firstProgram.result+' → '+latestProgram.result+'，共 '+pg.history.length+' 次运行':'尚无运行证据')+'</p>'
 +'<p><b>20题考核：</b>首次 '+(observedScore(s,true)??'未答')+' / '+observedTotal(s,true)+'；最近 '+(observedScore(s)??'未提交')+' / '+observedTotal(s)+'</p>'
 +'<p><b>提示展开：</b>'+['manual','design','obstacle'].map(id=>(r[id]?.hints||0)+'/3').join('、')+'（不扣分）</p>'
 +'<p><b>建议追问：</b>'+E(o?.prediction&&o.prediction!=='blocked'?'遇障碍后的动作由哪条规则决定？':pg?.history?.length&&!Rules.completed('program',pg)?'程序在第几条出错？你如何修改并重新验证？':m&&!Rules.completed('manual',m)?'回看一个转弯：观察、动作和结果分别是什么？':'请学生选一次修改，用运行结果解释理由。')+'</p></div></div>';
}
function stageStatus(s,stage){const current=Rules.completed(stage.id,s.payload.records[stage.id]),awarded=s.awards.some(a=>a.stage===stage.id);if(current)return '✓ 当前完成';if(awarded)return '曾完成 · 待验证';return s.payload.records[stage.id]?'进行中':'未开始';}
function renderClass(){
 const el=document.querySelector('#classContent');if(!el)return;
 const total=students.length,active=students.filter(s=>s.entered),entered=active.length,complete=active.filter(s=>currentCount(s)===Rules.stages.length).length,manual=students.filter(s=>s.manual).length;
 const answered=students.filter(s=>observedScore(s,true)!==null),correct=answered.filter(s=>observedScore(s,true)===observedTotal(s,true)).length;
 const introAnswered=active.filter(s=>s.payload.records.intro?.first),startMisconception=introAnswered.filter(s=>s.payload.records.intro.first[0]===0).length;
 const designs=active.filter(s=>s.payload.records.design?.tested),designIssues=designs.filter(s=>!Rules.design(s.payload.records.design).ok),designExample=designIssues[0]?.payload.records.design.result||'尚无典型错例';
 const obstacles=active.filter(s=>s.payload.records.obstacle?.originalTested),predictionMismatch=obstacles.filter(s=>s.payload.records.obstacle.prediction!=='blocked').length;
 el.innerHTML='<div class="stats">'+[['班级人数',total],['已进入',entered],['未进入',total-entered],['进行中',entered-complete],['当前主线完成',complete]].map(([t,n])=>'<div class="stat"><small>'+t+'</small><strong>'+n+'</strong></div>').join('')+'</div><p class="mini-label">统计分母：当前班级 '+total+' 人（含手动加入 '+manual+' 人）。“当前完成”依据最近方案；历史积分不因重玩扣除。</p><div class="insight-grid"><article><small>启动与控制</small><strong>'+startMisconception+' / '+introAnswered.length+'</strong><p>'+startMisconception+' 人首答认为“启动就一定能送好”。</p><b>追问：启动以后，谁在决定转向和停止？</b></article><article><small>任务与结果</small><strong>'+designIssues.length+' / '+designs.length+'</strong><p>'+designIssues.length+' 份最近方案仍有送达、停止或提醒问题。</p><b>'+(!designIssues.length?'尚无需要全班干预的典型错例。':'匿名片段：'+E(designExample))+'</b></article><article><small>规则与恢复</small><strong>'+predictionMismatch+' / '+obstacles.length+'</strong><p>'+predictionMismatch+' 人对原方案遇到障碍的预测与仿真不一致。</p><b>追问：纸箱移走后，什么条件让机器人继续？</b></article></div><div class="mini-progress">'+Rules.stages.map(st=>'<span>'+st.title+' <b>'+students.filter(s=>Rules.completed(st.id,s.payload.records[st.id])).length+' / '+total+'</b></span>').join('')+'</div><div class="mission-note" style="margin-bottom:18px">20题考核首答全对：'+correct+' / '+answered.length+' 名已作答学生；未作答 '+(total-answered.length)+' 人。'+(answered.length?'可展开个人记录，比较首次与最近表现。':'尚无首答证据，暂不判断掌握情况。')+'</div><div class="table-scroll"><table><thead><tr><th>姓名</th><th>当前环节</th>'+Rules.stages.map(s=>'<th>'+s.title+'</th>').join('')+'<th>当前进度</th><th>历史积分</th><th>检验首答/最近</th><th>最近同步</th><th>证据</th></tr></thead><tbody>'+students.filter(s=>s.name.includes(query)&&(!onlyIncomplete||currentCount(s)<Rules.stages.length)).map(s=>'<tr><td>'+E(s.name)+(s.manual?' <small>手动</small>':'')+'</td><td>'+E(s.entered?(Rules.stages.find(t=>t.id===s.payload.stage)?.title||'已进入'):'尚未进入')+'</td>'+Rules.stages.map(st=>'<td>'+stageStatus(s,st)+'</td>').join('')+'<td>'+currentCount(s)+'/'+Rules.stages.length+' · '+Math.round(currentCount(s)/Rules.stages.length*100)+'%</td><td>'+s.points+'</td><td>'+(observedScore(s,true)??'—')+'/'+observedTotal(s,true)+'；'+(observedScore(s)??'—')+'/'+observedTotal(s)+'</td><td>'+time(s.updated)+'</td><td><button data-detail="'+E(s.id)+'">'+(opened===s.id?'收起':'展开')+'</button></td></tr>'+(opened===s.id?'<tr class="detail-row"><td colspan="14">'+detail(s)+'</td></tr>':'')).join('')+'</tbody></table></div>';
 el.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{opened=opened===b.dataset.detail?'':b.dataset.detail;renderClass();});
}
document.querySelector('#teacherLogout').onclick=async()=>{try{await api('/api/logout',{role:'teacher'});entry();}catch(e){alert(e.message);}};
start();
