'use strict';
const T=document.querySelector('#teacherApp'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let classId='601',students=[],lastAt=null,query='',onlyIncomplete=false,opened='',timer=null,requestSeq=0;
async function api(url,data){const res=await fetch(url,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const b=await res.json();if(!res.ok){const e=Error(b.error);e.status=res.status;throw e;}return b;}
function count(s){return s.awards.length;}
function currentCount(s){return Rules.stages.filter(stage=>Rules.completed(stage.id,s.payload.records[stage.id])).length;}
function time(v){return v?new Date(v).toLocaleTimeString('zh-CN',{hour12:false}):'尚无记录';}
function entry(){clearInterval(timer);document.querySelector('#teacherLogout').hidden=true;document.querySelector('#teacherTestLink').hidden=true;T.innerHTML='<section class="login-card" style="max-width:440px;margin:8vh auto"><div class="eyebrow">教师入口</div><h2>查看学习过程</h2><p class="muted">教师大屏密码为 <b>teacher</b>。</p><form id="teacherForm"><label for="teacherPassword">教师密码</label><input id="teacherPassword" type="password" autocomplete="current-password" required><button class="primary">进入班级大屏</button></form><p class="error" id="teacherError" role="alert"></p></section>';document.querySelector('#teacherForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/teacher/login',{password:document.querySelector('#teacherPassword').value});await start();}catch(err){document.querySelector('#teacherError').textContent=err.message;}};}
async function start(){document.querySelector('#teacherLogout').hidden=false;document.querySelector('#teacherTestLink').hidden=false;T.innerHTML='<div class="task-heading"><div><div class="eyebrow">课堂观察 / 我是小小控制员</div><h1 style="font-size:29px;margin:0">看见学生怎样控制、怎样修改</h1></div><span id="updated" class="status">正在读取课堂记录…</span></div><div class="teacher-toolbar"><label for="teacherClass">班级</label><select id="teacherClass">'+['601','602','603','604','605','606'].map(c=>'<option value="'+c+'" '+(c===classId?'selected':'')+'>'+c+'班</option>').join('')+'</select><input id="studentSearch" aria-label="查找姓名" placeholder="查找姓名"><button id="filterIncomplete">只看未完成</button><button id="exportClass">导出当前班级记录</button></div><div id="classContent"></div>';document.querySelector('#teacherClass').onchange=e=>{classId=e.target.value;opened='';students=[];renderClass();load();};document.querySelector('#studentSearch').oninput=e=>{query=e.target.value;renderClass();};document.querySelector('#filterIncomplete').onclick=e=>{onlyIncomplete=!onlyIncomplete;e.target.classList.toggle('selected',onlyIncomplete);renderClass();};document.querySelector('#exportClass').onclick=()=>{const b=new Blob([JSON.stringify({lesson:'我是小小控制员',classId,exportedAt:new Date().toISOString(),students},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=classId+'班-配送实验记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};await load();clearInterval(timer);timer=setInterval(load,4000);}
async function load(){const seq=++requestSeq,requested=classId;try{const d=await api('/api/teacher/class?class='+requested);if(seq!==requestSeq||requested!==classId)return;students=d.students;lastAt=d.at;renderClass();document.querySelector('#updated').textContent='自动更新 · '+time(lastAt);document.querySelector('#updated').className='status';}catch(e){if(e.status===401){entry();return;}if(document.querySelector('#updated')){document.querySelector('#updated').textContent='连接异常 · 当前显示 '+time(lastAt)+' 的记录';document.querySelector('#updated').className='status warning';}}}
function observedScore(s,first=false){return Rules.assessmentScore(s.payload.records.assessment,first?'first':'latest');}
function detail(s){const r=s.payload.records,m=r.manual,d=r.design,o=r.obstacle;const control=m?.situation&&m?.keyAction&&m?.outcome?({corner:'看到转角',receiver:'看到进入接收区','need-observe':'需要看清位置'}[m.situation]||m.situation)+' → '+({left:'左转',right:'右转',stop:'停止',slow:'慢速',normal:'常速'}[m.keyAction]||m.keyAction)+' → '+({'new-direction':'沿新方向前进','stopped-target':'停在目标位置','speed-changed':'移动快慢改变'}[m.outcome]||m.outcome):'尚无完整证据';return '<div class="detail-grid"><div><h3>操作与设计证据</h3><p><b>导入首答：</b>'+E(r.intro?.first?JSON.stringify(r.intro.first.map((x,i)=>i===0?(x===1?'认为启动后还要看怎样运行':'认为启动就能送好'):(x===0?'认为方向由人或规则决定':'认为车轮知道目的地'))):'尚无证据')+'</p><p><b>手动控制：</b>'+(m?E((m.actions||[]).filter(x=>x!=='tick').map(x=>({go:'前进',stop:'停止',left:'左转',right:'右转',slow:'慢速',normal:'常速'}[x])).slice(-30).join(' → ')):'尚无证据')+'</p><p><b>关键控制证据：</b>'+E(control)+'</p><p><b>首次方案：</b>'+E(d?.first?d.first.steps.map(x=>({travel:'前往',stop:'停止',notify:'提醒'}[x])).join(' → '):'尚无证据')+'</p><p><b>当前提醒：</b>'+E(d?.noticeMode?({light:'提示灯',sound:'轻声提示音＋文字'}[d.noticeMode]||d.noticeMode)+'；'+({quiet:'保持安静',hear:'不看画面也能听见'}[d.noticeReason]||'尚未说明理由'):'尚无证据')+'</p><p><b>最近测试：</b>'+E(d?.result||'尚无证据')+'</p></div><div><h3>验证与后续支持</h3><p><b>障碍预测：</b>'+E({blocked:'原方案会受阻',continue:'会穿过纸箱',detour:'会自动绕路'}[o?.prediction]||'尚无证据')+'</p><p><b>所选规则：</b>'+E({wait:'停止等待，通道恢复后继续',help:'停止求助，管理员确认继续'}[o?.policy]||'尚无证据')+'</p><p><b>最新结果：</b>'+E(o?.result||'尚无证据')+'</p><p><b>独立检验：</b>首次 '+(observedScore(s,true)??'未答')+' / 3；最近 '+(observedScore(s)??'未提交')+' / 3</p><p><b>提示展开：</b>'+['manual','design','obstacle'].map(id=>(r[id]?.hints||0)+'/3').join('、')+'（不扣分）</p><p><b>建议追问：</b>'+E(o?.prediction&&o.prediction!=='blocked'?'纸箱移走前后，机器人的规则和动作有什么关系？':m&&!Rules.completed('manual',m)?'回看一个转弯：你看到了什么，做了什么，结果如何？':d?.tested&&!Rules.design(d).ok?'当前运行结果满足“送达、停好、提醒”了吗？':'请学生选一次修改，用运行结果解释修改理由。')+'</p></div></div>';}
function stageStatus(s,stage){const current=Rules.completed(stage.id,s.payload.records[stage.id]),awarded=s.awards.some(a=>a.stage===stage.id);if(current)return '✓ 当前完成';if(awarded)return '曾完成 · 待验证';return s.payload.records[stage.id]?'进行中':'未开始';}
function renderClass(){
 const el=document.querySelector('#classContent');if(!el)return;
 const total=students.length,active=students.filter(s=>s.entered),entered=active.length,complete=active.filter(s=>currentCount(s)===5).length,manual=students.filter(s=>s.manual).length;
 const answered=students.filter(s=>observedScore(s,true)!==null),correct=answered.filter(s=>observedScore(s,true)===3).length;
 const introAnswered=active.filter(s=>s.payload.records.intro?.first),startMisconception=introAnswered.filter(s=>s.payload.records.intro.first[0]===0).length;
 const designs=active.filter(s=>s.payload.records.design?.tested),designIssues=designs.filter(s=>!Rules.design(s.payload.records.design).ok),designExample=designIssues[0]?.payload.records.design.result||'尚无典型错例';
 const obstacles=active.filter(s=>s.payload.records.obstacle?.originalTested),predictionMismatch=obstacles.filter(s=>s.payload.records.obstacle.prediction!=='blocked').length;
 el.innerHTML='<div class="stats">'+[['班级人数',total],['已进入',entered],['未进入',total-entered],['进行中',entered-complete],['当前主线完成',complete]].map(([t,n])=>'<div class="stat"><small>'+t+'</small><strong>'+n+'</strong></div>').join('')+'</div><p class="mini-label">统计分母：当前班级 '+total+' 人（含手动加入 '+manual+' 人）。“当前完成”依据最近方案；历史积分不因重玩扣除。</p><div class="insight-grid"><article><small>启动与控制</small><strong>'+startMisconception+' / '+introAnswered.length+'</strong><p>'+startMisconception+' 人首答认为“启动就一定能送好”。</p><b>追问：启动以后，谁在决定转向和停止？</b></article><article><small>任务与结果</small><strong>'+designIssues.length+' / '+designs.length+'</strong><p>'+designIssues.length+' 份最近方案仍有送达、停止或提醒问题。</p><b>'+(!designIssues.length?'尚无需要全班干预的典型错例。':'匿名片段：'+E(designExample))+'</b></article><article><small>规则与恢复</small><strong>'+predictionMismatch+' / '+obstacles.length+'</strong><p>'+predictionMismatch+' 人对原方案遇到障碍的预测与仿真不一致。</p><b>追问：纸箱移走后，什么条件让机器人继续？</b></article></div><div class="mini-progress">'+Rules.stages.map(st=>'<span>'+st.title+' <b>'+students.filter(s=>Rules.completed(st.id,s.payload.records[st.id])).length+' / '+total+'</b></span>').join('')+'</div><div class="mission-note" style="margin-bottom:18px">独立检验首答全对：'+correct+' / '+answered.length+' 名已作答学生；未作答 '+(total-answered.length)+' 人。'+(answered.length?'可展开个人记录，比较首次与最近表现。':'尚无首答证据，暂不判断掌握情况。')+'</div><div class="table-scroll"><table><thead><tr><th>姓名</th><th>当前环节</th>'+Rules.stages.map(s=>'<th>'+s.title+'</th>').join('')+'<th>当前进度</th><th>历史积分</th><th>检验首答/最近</th><th>最近同步</th><th>证据</th></tr></thead><tbody>'+students.filter(s=>s.name.includes(query)&&(!onlyIncomplete||currentCount(s)<5)).map(s=>'<tr><td>'+E(s.name)+(s.manual?' <small>手动</small>':'')+'</td><td>'+E(s.entered?(Rules.stages.find(t=>t.id===s.payload.stage)?.title||'已进入'):'尚未进入')+'</td>'+Rules.stages.map(st=>'<td>'+stageStatus(s,st)+'</td>').join('')+'<td>'+currentCount(s)+'/5 · '+(currentCount(s)*20)+'%</td><td>'+s.points+'</td><td>'+(observedScore(s,true)??'—')+' / '+(observedScore(s)??'—')+'</td><td>'+time(s.updated)+'</td><td><button data-detail="'+E(s.id)+'">'+(opened===s.id?'收起':'展开')+'</button></td></tr>'+(opened===s.id?'<tr class="detail-row"><td colspan="12">'+detail(s)+'</td></tr>':'')).join('')+'</tbody></table></div>';
 el.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>{opened=opened===b.dataset.detail?'':b.dataset.detail;renderClass();});
}
document.querySelector('#teacherLogout').onclick=async()=>{try{await api('/api/logout',{role:'teacher'});entry();}catch(e){alert(e.message);}};
start();
